### ISSUE TITLE
Type Error: method.toUpperCase() is not function

### ISSUE THREAD

**Issue by rodrigohassel** [rocketseat-education/bootcamp-gostack-modulos#1]
https://github.com/rocketseat-education/bootcamp-gostack-modulos/blob/61c898fd9799debd8164b44ae800ce01a4bf409f/nivel-01/01-backend-com-node/src/index.js#L36

Ao realizar o start do servidor do backend está aceitando, porém ao utlizar o Insomnia acusa erro de Typer Error conforme o título da Issue sugere.

A princípio é só retirar os parêntesesq que ficará de boa.

**Comment by danilo-vieira** [comment]
Obrigado pela issue!
Problema resolvido :)
