### ISSUE TITLE
Argument of type 'string' is not assignable to parameter of type 'SetStateAction<never[]>'

### ISSUE THREAD

**Issue by rogersebastiany** [rocketseat-education/bootcamp-gostack-modulos#7]
em nivel-03/01-primeiro-projeto-com-react/src/pages/Dashboard/index.tsx:43
`          onChange={e => setNewRepo(e.target.value)}`
ocorre o erro 
`Argument of type 'string' is not assignable to parameter of type 'SetStateAction<never[]>'`

@danilo-vieira

**Comment by rogersebastiany** [comment]
Argument of type 'string' is not assignable to parameter of type 'SetStateAction<never[]>'.ts(2345)

**Comment by danilo-vieira** [comment]
Olá @rogersebastiany 
Você pode abrir um novo tópico no fórum com esse problema? Assim o nosso time consegue te ajudar melhor 💜
